config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # Profile
  get 'profile', to: 'users#profile'
  
  # Resources  
  resources :users
  
  resources :requisitions do
    resources :references
  end

  # Root
  root 'home#index'
  
end

app/models/requisition.rb
class Requisition < ApplicationRecord
  belongs_to :user
  has_many :references
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_requisition, only: [:show, :edit, :update, :destroy]

  # GET /requisitions
  # GET /requisitions.json
  def index
    @requisitions = current_user.requisitions.all
  end

  # GET /requisitions/1
  # GET /requisitions/1.json
  def show    
  end

  # GET /requisitions/new
  def new
    @requisition = Requisition.new
  end

  # GET /requisitions/1/edit
  def edit
    @reference = Reference.new
    # @references = current_user.requisitions
  end

  # POST /requisitions
  # POST /requisitions.json
  def create
    @requisition = current_user.requisitions.new(requisition_params)

    respond_to do |format|
      if @requisition.save
        format.html { redirect_to @requisition, notice: 'La solicitud fue creada con éxito.' }
        format.json { render :show, status: :created, location: @requisition }
      else
        format.html { render :new }
        format.json { render json: @requisition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requisitions/1
  # PATCH/PUT /requisitions/1.json
  def update
    respond_to do |format|
      if @requisition.update(requisition_params)
        format.html { redirect_to @requisition, notice: 'La solicitud se actualizó con éxito.' }
        format.json { render :show, status: :ok, location: @requisition }
      else
        format.html { render :edit }
        format.json { render json: @requisition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requisitions/1
  # DELETE /requisitions/1.json
  def destroy
    @requisition.destroy
    respond_to do |format|
      format.html { redirect_to requisitions_url, notice: 'La solicitud se eliminó correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requisition
      @requisition = current_user.requisitions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requisition_params
      params.require(:requisition).permit(:user_id, :income, :address_years, :marital_status, :dependents_number, :requested_amount, :payment_terms, 
                                          :bank, :company_name, :company_phone_number, :company_position, :company_years, :has_sgmm, :has_imss, :has_car, :comment)
    end
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
end

app/views/requisitions/_form.html.erb
<%= form_for(requisition) do |f| %>
  <% if requisition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(requisition.errors.count, "error") %> prohibited this requisition from being saved:</h2>

      <ul>
      <% requisition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.label :income, "¿Ingresos mensuales?" %> <small class="text-danger">*</small>
      <%= f.text_field :income, class: "form-control", :required => true %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <%= f.label :address_years, "¿Cuántos años tiene viviendo en su domicilio actual?" %> <small class="text-danger">*</small>
      <%= f.number_field :address_years, class: "form-control", min: 0, :required => true %>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.label :marital_status, "¿Estado civil?" %>
      <%= f.select(:marital_status, options_for_select([
            ['Soltero', 'Soltero'], 
            ['Casado', 'Casado'],
            ['Divorciado', 'Divorciado'],
            ['Viudo', 'Viudo']
            ], requisition.marital_status),{},{class: "form-control"}) %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <%= f.label :dependents_number, "¿Cuántas personas dependen de usted?" %> <small class="text-danger">*</small>
      <%= f.number_field :dependents_number, class: "form-control", min: 0, :required => true %>
    </div>    
  </div>


   <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= f.label :requested_amount, "¿Monto que solicita?" %> <small class="text-danger">*</small>
      <%= f.number_field :requested_amount, class: "form-control", :required => true, :min => 1 %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= f.label :payment_terms, "Términos de pago" %>
      <%= f.text_field :payment_terms, class: "form-control" %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= f.label :bank, "¿Banco?" %>
      <%= f.text_field :bank, class: "form-control", :required => true %>
    </div>
  </div>


   <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.label :company_name, "¿Nombre de la empresa donde trabaja?" %> <small class="text-danger">*</small>
      <%= f.text_field :company_name, class: "form-control", :required => true %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <%= f.label :company_phone_number, "¿Teléfono de la empresa?" %> <small class="text-danger">*</small>
      <%= f.text_field :company_phone_number, class: "form-control", :required => true %>
    </div>    
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= f.label :company_position, "¿Posición en la empresa?" %>
      <%= f.text_field :company_position, class: "form-control" %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <%= f.label :company_years, "¿Cuantos años tiene trabajando en la empresa?" %> <small class="text-danger">*</small>
      <%= f.number_field :company_years, class: "form-control", :required => true, :min => 1  %>
    </div>    
  </div>


  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <%= f.label :has_sgmm, "¿Tiene seguro de gastos médicos mayores?" %> <small class="text-danger">*</small>
      <%= f.select(:has_sgmm, options_for_select([['Si', true], ['No', false]], requisition.has_sgmm),{},{class: "form-control"}) %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= f.label :has_imss, "¿Tiene IMSS?" %> <small class="text-danger">*</small>
      <%= f.select(:has_imss, options_for_select([['Si', true], ['No', false]], requisition.has_imss),{},{class: "form-control"}) %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <%= f.label :has_car, "Tiene carro?" %> <small class="text-danger">*</small>
      <%= f.select(:has_car, options_for_select([['Si', true], ['No', false]], requisition.has_car),{},{class: "form-control"}) %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= f.label :comment, "Comentarios" %>
      <%= f.text_area :comment, class: "form-control" %>      
    </div>    
  </div>

  <br/>
  <div class="actions">
    <div class="col-xs-12 col-sm-3">
      <%= f.submit "Guardar", class: "btn btn-lg btn-success btn-block" %>
    </div>
  </div>  
  <br/>
<% end %>

app/views/requisitions/edit.html.erb
<div class="page-title">
  <div class="row">
    <h1 class="col-xs-12 col-sm-8">
      <i class="glyphicon glyphicon-edit page-title-icon"></i> Modificar solicitud
    </h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title">Llene los datos que se le piden a continuación</span>
  </div>
  <div class="panel-body">

		<%= render 'form', requisition: @requisition %>

    <div class="center-block">
  		<%= link_to 'Mostrar', @requisition %> |
  		<%= link_to 'Regresar', requisitions_path %>
    </div> 

	</div>	
  
  <br/>
  <div class="container-fluid">
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="panel-title">Referencias personales 
          <% if @requisition.references.size < 3 %>
            <b class="text-danger">(Debe de agregar 3 referencias personales)</b>
          <% end %>
        </span>
      </div>
      <div class="panel-body">

        <div>
          <% if @requisition.references.size < 3 %>
            <%= render "references/form" %>
          <% end if %>  
        </div>
          

        <table class="table table-striped">
          <thead>
            <tr>
              <th>Primer nombre</th>
              <th>Segundo nombre</th>
              <th>Primer apellido</th>
              <th>Segundo apellido</th>
              <th>Teléfono</th>
              <th>Modificar</th>
            <tr>
          </thead> 
          <tbody>
            <% @requisition.references.each do |reference| %>
              <tr>
                <td><%= reference.first_name %></td>
                <td><%= reference.second_name %></td>
                <td><%= reference.first_last_name %></td>
                <td><%= reference.second_last_name %></td>
                <td><%= reference.cell_phone_number %></td>
                <td>
                  <%= link_to glyph(:edit), edit_requisition_reference_path(@requisition, reference), :class => "btn btn-warning btn-default btn-round" %>
                </td>
              </tr>
            <% end %>
          </tbody> 
        </table>              
      </div>
    </div>
  </div>

</div>

app/views/requisitions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-title">
  <div class="row">
    <h1 class="col-xs-12 col-sm-8">
      <i class="fa fa-folder-open-o"></i> Solicitudes de crédito
    </h1>
    <div class="col-xs-12 col-sm-4">
      <div class="pull-right">        
        <%= link_to new_requisition_path, class: "btn btn-success btn-lg btn-labeled" do %>
          <span class="btn-label"><i class="glyphicon glyphicon-plus"></i></span>Agregar solicitud
        <% end %>
      </div>
    </div>          
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title">Solicitudes de crédito</span>
  </div>
  <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Id</th>
            <th>Fecha</th>            
            <th>Monto</th>
            <th>Comentarios</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @requisitions.each do |requisition| %>
            <tr>
              <td><%= requisition.id %></td>
              <td><%= requisition.created_at %></td>
              <td><%= requisition.requested_amount %></td>
              <td><%= requisition.comment %></td>
              <td> 
                <%= link_to glyph(:ok), requisition, :class => "btn btn-success btn-default btn-round" %>
                <%= link_to glyph(:edit), edit_requisition_path(requisition), :class => "btn btn-warning btn-default btn-round" %>
                <%= link_to glyph(:trash), requisition, method: :delete, :class => "btn btn-danger btn-default btn-round", data: { confirm: '¿Está seguro que desea eliminar el registro?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/requisitions/new.html.erb
<div class="page-title">
  <div class="row">
    <h1 class="col-xs-12 col-sm-8">
      <i class="glyphicon glyphicon-plus page-title-icon"></i> Agregar solicitud
    </h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title">Llene los datos que se le piden a continuación</span>
  </div>
  <div class="panel-body">

		<%= render 'form', requisition: @requisition %>

		<%= link_to 'Regresar', requisitions_path %>
	</div>	
</div>

app/views/requisitions/show.html.erb
<div class="page-title">
  <div class="row">
    <h1 class="col-xs-12 col-sm-8">
      <i class="fa fa-folder-open-o page-title-icon"></i> Datos de solicitud
    </h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title">Datos de la solicitud</span>
  </div>
  <div class="panel-body">

		<div class="panel panel-default">
			  <div class="panel-heading">
			    <span class="panel-title">Datos generales</span>
			  </div>
			  <div class="panel-body">
					<table class="table">
						<tr>
				      <th>Monto que solicita ($):</th>
				      <td class="text-danger"><b>$<%= @requisition.requested_amount %></b></td>
				    </tr>
				    <tr>
				      <th>Términos de pago:</th>
				      <td><%= @requisition.payment_terms %></td>
				    </tr>
				    <tr>
				      <th>Banco:</th>
				      <td><%= @requisition.bank %></td>
				    </tr>
				  </table>
				</div>
			</div>  

		<div class="panel panel-default">
			<div class="panel-heading">
				<span class="panel-title">Datos personales</span>
			</div>
		  <div class="panel-body">
				<table class="table">
				  <tbody>
				    <tr>
				      <th>Ingresos mensuales ($):</th>
				      <td>$<%= @requisition.income %></td>
				    </tr>
				    <tr>
				      <th>Años tiene viviendo en su domicilio actual:</th>
				      <td><%= @requisition.address_years %></td>
				    </tr>
				    <tr>
				      <th>Estado civil:</th>
				      <td><%= @requisition.marital_status %></td>
				    </tr>
				    <tr>
				      <th>Personas que dependen de usted:</th>
				      <td><%= @requisition.dependents_number %></td>
				    </tr>				    
				     <tr>
				      <th>Tiene Seguro de gastos médicos mayores</th>
				      <td><%= human_boolean(@requisition.has_sgmm) %></td>
				    </tr>
				    <tr>
				      <th>Tiene Imss</th>
				      <td><%= human_boolean(@requisition.has_imss) %></td>
				    </tr>
				    <tr>
				      <th>Tiene Carro</th>
				      <td><%= human_boolean(@requisition.has_car) %></td>
				    </tr>
					</table>
				</div>	
			</div>

			<div class="panel panel-default">
			  <div class="panel-heading">
			    <span class="panel-title">Datos de la empresa</span>
			  </div>
			  <div class="panel-body">
					<table class="table">
						<tr>
				      <th>Nombre de la empresa donde trabaja:</th>
				      <td><%= @requisition.company_name %></td>
				    </tr>
				    <tr>
				      <th>Teléfono de la empresa:</th>
				      <td><%= @requisition.company_phone_number %></td>
				    </tr>
				    <tr>
				      <th>Posición en la empresa</th>
				      <td><%= @requisition.company_position %></td>
				    </tr>
				    <tr>
				      <th>Años trabajando en la empresa</th>
				      <td><%= @requisition.company_years %></td>
				    </tr>
				  </table>
				</div>
			</div>  


	
	    <div class="panel panel-default">
	      <div class="panel-heading">
	        <span class="panel-title">Referencias personales 
          <% if @requisition.references.size < 3 %>
            <b class="text-danger">(Debe de agregar 3 referencias personales)</b>
          <% end %>
        </span>
	      </div>
	      <div class="panel-body">
					<table class="table table-striped">
	          <thead>
	            <tr>
	              <th>Primer nombre</th>
	              <th>Segundo nombre</th>
	              <th>Primer apellido</th>
	              <th>Segundo apellido</th>
	              <th>Teléfono</th>
	              <th>Modificar</th>
	            <tr>
	          </thead> 
	          <tbody>
	            <% @requisition.references.each do |reference| %>
	              <tr>
	                <td><%= reference.first_name %></td>
	                <td><%= reference.second_name %></td>
	                <td><%= reference.first_last_name %></td>
	                <td><%= reference.second_last_name %></td>
	                <td><%= reference.cell_phone_number %></td>
	                <td>
	                  <%= link_to glyph(:edit), edit_requisition_reference_path(@requisition, reference), :class => "btn btn-warning btn-default btn-round" %>
	                </td>
	              </tr>
	            <% end %>
	          </tbody> 
	        </table>
				</div>
			</div>
			
			<%= link_to 'Modificar', edit_requisition_path(@requisition) %> |
			<%= link_to 'Regresar', requisitions_path %>
		</div>

	</div>
</div>	