config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # Profile
  get 'profile', to: 'users#profile'
  
  # Resources  
  resources :users
  
  resources :requisitions do
    resources :references
  end

  # Root
  root 'home#index'
  
end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :user
  belongs_to :requisition

  validates :first_name, :presence => { :message => " no puede estar vacío" }
            
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update]
  before_action :set_requisition

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = current_user.references.new(reference_params)
    @reference.requisition = @requisition

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference.requisition, notice: 'La referencia se creó con éxito.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference.requisition, notice: 'La referencia se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'La referencia fue eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    def set_requisition 
      @requisition = Requisition.find(params[:requisition_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:user_id, :requisition_id, :first_name, :second_name, :first_last_name, :second_last_name, :cell_phone_number)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= form_for([@requisition, @reference]) do |f| %>
  <% if @reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12 col-sm-2">
      <%= f.label :first_name, "Primer nombre:" %> <small class="text-danger">*</small>
      <%= f.text_field :first_name, class: "form-control", placeholder: "Primer nombre", :required => true %>
    </div>

    <div class="col-xs-12 col-sm-2">
      <%= f.label :second_name, "Segundo nombre:" %>
      <%= f.text_field :second_name, class: "form-control", placeholder: "Segundo nombre" %>
    </div>

    <div class="col-xs-12 col-sm-2">
      <%= f.label :first_last_name, "Primer apellido:" %> <small class="text-danger">*</small>
      <%= f.text_field :first_last_name, class: "form-control", placeholder: "Primer apellido", :required => true %>
    </div>

    <div class="col-xs-12 col-sm-2">
      <%= f.label :second_last_name, "Segundo apellido:" %> <small class="text-danger">*</small>
      <%= f.text_field :second_last_name, class: "form-control", placeholder: "Segundo apellido", :required => true %>
    </div>

    <div class="col-xs-12 col-sm-2">
      <%= f.label :cell_phone_number, "Teléfono celular:" %> <small class="text-danger">*</small>
      <%= f.text_field :cell_phone_number, class: "form-control", placeholder: "Teléfono celular", :required => true %>
    </div>

    <div class="col-xs-12 col-sm-2"><br/>     
     <%= f.submit "Guardar", class: "btn btn-primary btn-block" %>
    </div>
  </div>
 
<% end %>

<br/><br/>

app/views/references/edit.html.erb
<div class="page-title">
  <div class="row">
    <h1 class="col-xs-12 col-sm-8">
      <i class="glyphicon glyphicon-edit page-title-icon"></i> Modificar referencia
    </h1>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <span class="panel-title">Llene los datos que se le piden a continuación</span>
  </div>
  <div class="panel-body">
		<%= render 'form', reference: @reference %>
	</div>
</div>



<%= link_to 'Regresar', edit_requisition_path(@requisition) %>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Requisition</th>
      <th>First name</th>
      <th>Second name</th>
      <th>First last name</th>
      <th>Second last name</th>
      <th>Cell phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.requisition %></td>
        <td><%= reference.first_name %></td>
        <td><%= reference.second_name %></td>
        <td><%= reference.first_last_name %></td>
        <td><%= reference.second_last_name %></td>
        <td><%= reference.cell_phone_number %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requisition:</strong>
  <%= @reference.requisition %>
</p>

<p>
  <strong>First name:</strong>
  <%= @reference.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @reference.second_name %>
</p>

<p>
  <strong>First last name:</strong>
  <%= @reference.first_last_name %>
</p>

<p>
  <strong>Second last name:</strong>
  <%= @reference.second_last_name %>
</p>

<p>
  <strong>Cell phone number:</strong>
  <%= @reference.cell_phone_number %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>